### ISSUE TITLE
Can't Connect to ClickHouse

### ISSUE THREAD

**Issue by lovatti** [Canner/WrenAI#1005]
**Describe the bug**

I'm trying to connect to ClickHouse self-hosted server without success.

**To Reproduce**

1. Go to 'http://localhost:3000/setup/connection'
2. Click on 'Connect to a Datasource -> ClickHouse'
3. Scroll down to 'Fill the form'

**Expected behavior**

It should connect to ClickHouse, but I get an error.

Internal server error
Cannot read properties of undefined (reading 'data')
Inspecting the page, I can see
ApolloError: Cannot read properties of undefined (reading 'data')

Using the console terminal of the same wrenai service in Docker Desktop, trying wget works fine to connect to ClickHouse.

PS. I'm using port 443 instead of 8443 because I'm proxying connections to ClickHouse via Nginx reverse proxy.

**Screenshots**

![wrenai_x_ch1](https://github.com/user-attachments/assets/241ea0c9-ce15-423c-82c5-4f95b5764059)

**Desktop (please complete the following information):**

- OS: Linux Mint 22 Cinnamon (Cinnamon 6.2.9, Linux Kernel 6.8.0-50-generic)
- Browser: Firefox 133.0.3

**Wren AI Information**

- Version: wren-ui 0.17.3, wren-ai-service 0.11.8, wren-engine 0.12.1
- LLM_PROVIDER= openai_llm
- GENERATION_MODEL= gpt-3.5

**Additional context**

Docker Desktop started WrenAI successfully.
WrenAI working as expected if using E-commerce and Human Resource sample databases.
ClickHouse is working fine for months.

Any thoughts?

Thank you!

Bruno

**Comment by wwwy3y3** [comment]
@grieve54706 could you take a look? thanks

**Comment by grieve54706** [comment]
Hi @lovatti, could you provide the log via command line:
```bash
docker logs wrenai-wren-engine-1 >& wrenai-wren-engine.log && \
docker logs wrenai-ibis-server-1 >& wrenai-ibis-server.log
```
