### ISSUE TITLE
Wren ai service ERROR: Application startup failed. Exiting

### ISSUE THREAD

**Issue by istvanszab** [Canner/WrenAI#1030]
**Describe the bug**
I am following this tutorial: [How to use Meta Llama 3 to query MySQL database using Ollama and Wren AI](https://getwren.ai/post/how-to-use-meta-llama-3-to-query-mysql-database-using-ollama-and-wren-ai) and [Running Wren AI with your Custom LLM, Embedder or Document Store](https://docs.getwren.ai/oss/installation/custom_llm)
The wren ai service failed to start

**Desktop (please complete the following information):**
- MS Windows 10 ver. 22H2

**Wren AI Information**
- Version: 0.12.0
- LLM_PROVIDER= ollama_llm
- GENERATION_MODEL= llama3:8b

**Config files**
Attached
[config.yaml.txt](https://github.com/user-attachments/files/18202035/config.yaml.txt)
[env.ai.txt](https://github.com/user-attachments/files/18202036/env.ai.txt)

**Relevant log output**
Logs attached
[wrenai-ibis-server-1.txt](https://github.com/user-attachments/files/18201932/wrenai-ibis-server-1.txt)
[wrenai-qdrant-1.txt](https://github.com/user-attachments/files/18201933/wrenai-qdrant-1.txt)
[wrenai-wren-ai-service-1.txt](https://github.com/user-attachments/files/18201934/wrenai-wren-ai-service-1.txt)
[wrenai-wren-engine-1.txt](https://github.com/user-attachments/files/18201935/wrenai-wren-engine-1.txt)

**Comment by istvanszab** [comment]
@cyyeh thank you for your fast response. I am waiting for the new release.

**Comment by cyyeh** [comment]
@istvanszab The new release is here: https://github.com/Canner/WrenAI/releases/tag/0.13.0

**Comment by istvanszab** [comment]
@cyyeh It still doesn't work.
I attach the wren ai service log.
[wrenai-wren-ai-service-1.txt](https://github.com/user-attachments/files/18212143/wrenai-wren-ai-service-1.txt)

**Comment by cyyeh** [comment]
@istvanszab  could you provide config.yaml and .env file with me(and replace sensitive data with some keywords)?

**Comment by istvanszab** [comment]
@cyyeh These are in my first post. I attach the files again.
[config.yaml.txt](https://github.com/user-attachments/files/18213510/config.yaml.txt)
[env.ai.txt](https://github.com/user-attachments/files/18213511/env.ai.txt)

**Comment by cyyeh** [comment]
We don't use .env.ai anymore. Please follow the documentation I provide above first.

**Comment by istvanszab** [comment]
@cyyeh I delete the .env.ai and make some chenges my config.yaml. It still doesn't work.
I atach the config.yaml and the service log.
[config.yaml.txt](https://github.com/user-attachments/files/18214008/config.yaml.txt)
[wrenai-wren-ai-service-1.txt](https://github.com/user-attachments/files/18214009/wrenai-wren-ai-service-1.txt)

**Comment by cyyeh** [comment]
@istvanszab where is your .env file?

**Comment by istvanszab** [comment]
@cyyeh The .env attached.
The pipeline definitions are used again.
I followed your instructions but still doesn't work.
[env.txt](https://github.com/user-attachments/files/18214362/env.txt)

**Comment by cyyeh** [comment]
@istvanszab could you join our Discord server? https://discord.gg/5DvshJqG8Z And we can schedule a time for meeting. You could share your screen with me and we could solve the issue together. Right now it is really inefficient to solve the issue.

**Comment by cyyeh** [comment]
fixed

**Comment by istvanszab** [comment]
@cyyeh Thank you very much your help.
