### ISSUE TITLE
Installtion issue 

### ISSUE THREAD

**Issue by RishandRish** [Canner/WrenAI#1037]
![Screenshot 2024-12-21 023557](https://github.com/user-attachments/assets/a0eb922f-0341-42a4-815c-16499f4a0800)
![Screenshot 2024-12-21 023535](https://github.com/user-attachments/assets/f9dcdd4c-7aa9-45b6-892c-a12aa4576da9)
after many tries i was failed to deploy (its say check logs ) when i check the log in ui docker its says not connected to servcies if i go services in there it will show like ui is not connecting (even its showin the same network, please give the installtion guidelance in linux

**Comment by cyyeh** [comment]
@RishandRish 
Hi thanks for reaching out, please attach ui and ai container logs thanks

**Comment by tsh2018** [comment]
我也是这样，我是在win部署的，蹲一个解决方案

**Comment by RishandRish** [comment]
hi send logs in discord

**Comment by cyyeh** [comment]
@RishandRish  @tsh2018 
We've just released a patch, please try this one!
https://github.com/Canner/WrenAI/releases/tag/0.13.1
