### ISSUE TITLE
Failed to ask a question, if import a sample dataset before start the AI service

### ISSUE THREAD

**Issue by ReddHung** [Canner/WrenAI#170]
**Describe the bug**
If a sample dataset is imported before the AI service has finished starting up, the AI service may respond with an error when asked a question.

**To Reproduce**
1. install from wren-launcher-darwin binary v0.2.0
2. selecting a sample dataset as soon as the WrenAI UI opens. (usually  AI service has not finished starting up)
3. ask question from WrenAI UI
4. See error "Failed to create asking task"

**Screenshots**
<img width="1078" alt="wrenai_ui_log" src="https://github.com/Canner/WrenAI/assets/13216113/59c6d40b-eee6-43e4-ab0b-1825c47d9855">
<img width="724" alt="wrenai_ai_log" src="https://github.com/Canner/WrenAI/assets/13216113/da42d5ec-33a8-4837-bfa8-7b03374e095a">
<img width="973" alt="wrenai_browser" src="https://github.com/Canner/WrenAI/assets/13216113/8eb54d9f-2749-46c4-9ea1-2a9848d824f1">

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1
 - Docker: v4.29.0
 - Browser: Chrome

**WrenAI Information**
- Version: 0.2.0

**Comment by wwwy3y3** [comment]
@ReddHung thanks for reporting.

We'll see if we can add some kind of mechanism that wait for AI service & engine to start before we serve user requests.

cc @onlyjackfrost

**Comment by onlyjackfrost** [comment]
fix in PR #220
