### ISSUE TITLE
Feature: support MS SQL Server connector 

### ISSUE THREAD

**Issue by ssword62** [Canner/WrenAI#173]
As many enterprises utilize Microsoft SQL Server for critical data storage and business operations, the integration of an MS SQL Server connector would be immensely beneficial. This feature would enable an additional critical provider.
I believe adding MS SQL Server support will be a strategic enhancement that will broaden WrenAI's usage and provide significant value to the user community.

**Comment by wwwy3y3** [comment]
If you think MSSQL is important to you. Please upvote here: https://github.com/Canner/WrenAI/discussions/327#discussioncomment-9578158

**Comment by cyyeh** [comment]
Guys, we now support MS SQL Server in our latest version! https://github.com/Canner/WrenAI/releases/tag/0.6.0

Please have a try and we look forward to your feedback ❤️

I'll close this issue now

**Comment by edisun3003** [comment]
its not working
