### ISSUE TITLE
Show internal server error message

### ISSUE THREAD

**Issue by swwu91** [Canner/WrenAI#175]
Currently when a internal server error occurs, we only show 'internal server error'.
In this use case, this error occurs because wifi is down:
![SCR-20240429-mmgv](https://github.com/Canner/WrenAI/assets/103988255/13281682-0ef8-440e-900b-711140bb3f15)

Should show error message(e.g. network error, unable to connect to network....) to let users know what is wrong.

**Comment by wwwy3y3** [comment]
@swwu91 thanks for reporting issue!

We successfully reproduce this error by manually disconnecting network on laptop. We'll improve this part in the following releases.
