### ISSUE TITLE
OpenAI key invalid AI service keep crashing

### ISSUE THREAD

**Issue by chilijung** [Canner/WrenAI#209]
**Describe the bug**
As title

**To Reproduce**
1. type in an invalid AI token or OpenAI read-only API token
2. The AI service will keep crashing.

**Expected behavior**
Invalid token should not keep AI service crashing.

**Screenshots**

<img width="1417" alt="image" src="https://github.com/Canner/WrenAI/assets/1216029/7f8358e2-66a8-494b-8a6a-d5eee8b7fb83">

**WrenAI Information**
- Version: v0.3.0-rc1

**Comment by cyyeh** [comment]
please make sure the OpenAI key provided has full permission: https://help.openai.com/en/articles/8867743-assign-api-key-permissions
