### ISSUE TITLE
How to change to local model interface

### ISSUE THREAD

**Issue by PoleGeogry** [Canner/WrenAI#212]
A large language model has been deployed locally. How to replace the openai interface with the local model interface?

**Comment by cyyeh** [comment]
@PoleGeogry hi, thanks for reaching out! Just to clarify a bit, are you using Ollama to deploy local large language models?

**Comment by PoleGeogry** [comment]
Indeed, can you give me some help, replace the openai related to calling local Ollama

**Comment by cyyeh** [comment]
@PoleGeogry Sure. Now we are using Haystack as the framework to develop generative AI apps. According to the official documentation from Haystack, it supports Ollama already(https://docs.haystack.deepset.ai/reference/integrations-ollama).

As of how to replace the openai to Ollama, I recommend you several places to look at:
1. in `wren-ai-service/src/globals.py`, we initialize our "services", and you can see a function called init_generator
2. in `wren-ai-service/src/pipelines/ask/components/generator.py` and `wren-ai-service/src/pipelines/ask_details/components/generator.py`, you can see how we initialize OpenAI generator. I think this is where you can define Ollama generator
3. there may be some inconsistencies here, for example, in `wren-ai-service/src/pipelines/semantics/description.py`, you can also see we defined an open ai generator here.

We welcome you to issue a PR or tell us how you are going to add Ollama first, and together we can make the codebase cleaner and better :) thanks again for your contribution!

**Comment by cyyeh** [comment]
@PoleGeogry  if you would like to add other llm or document store, please check out this branch: `feature/ai-service/unify-providers-interface`. We'll merge this branch soon.

I've done some changes in order for you to easily add your preferred llm or document store. You need to do the following steps in the wren-ai-service directory:
1. create a new provider class that inherits from `LLMProvider` or `DocumentStoreProvider` in the `src/providers` directory
2. if you need to add new environment variables, please add them to the `.env.dev` and `.env.prod` files
3. add a new function to import your providers in the `src/utils.py` file
4. call the new function you created in `container.init_globals()` in the `src/__main__.py`

You can inspect `src/providers/llm/openai.py` and `src/providers/document_store/qdrant.py` to more easily grasp what I mean.

Feel free to ask me anything if you run into issues.
