### ISSUE TITLE
Feature: OracleDB Support

### ISSUE THREAD

**Issue by Ethan-Otto** [Canner/WrenAI#236]
I work at a company with many oracle databases. So oracle compatability or a template for how we can set it up ourselves would be great.

**Comment by wwwy3y3** [comment]
Hi @Ethan-Otto , thanks for this feature request.

We're actually working on using the [ibis-project](https://github.com/ibis-project/ibis) to connect to the datasource. The concept is that WrenAI generates ibis-executable SQL, which is then transformed to the specific datasource using the appropriate dialect. You can see how we invoke the ibis-project in the [Wren Engine repo branch](https://github.com/Canner/wren-engine/tree/feature/ibis-server). It's still a work in progress.

Once we finish refactoring to ibis, Oracle support will come next I think.

**Comment by wwwy3y3** [comment]
Hi all, upvote here https://github.com/Canner/WrenAI/discussions/327#discussioncomment-9578178 if you think Oracle is important to you as well.

**Comment by luca-iannelli** [comment]
Please implement oracle support! I work for an italian university and in Italy almost all universities use oracle for their informaton systems. It would be great to have this tool available to all the academic community. Thaks a lot.

**Comment by wwwy3y3** [comment]
Duplicated with https://github.com/Canner/WrenAI/issues/710. Closing this.
