### ISSUE TITLE
Consistent Failed to Connect Error - PostgreSQL

### ISSUE THREAD

**Issue by andre-scheinwald** [Canner/WrenAI#259]
**Describe the bug**
I've tried this using the wren-launcher-windows.exe as well as cloning the repo and launching it via docker-compose --env-file .env.local up

After launching using either method I fill in the Display Name, Host, Port, Username, Password, and Database Name.  I consistently get a "Failed to Connect
Cannot connect to data source"
error message.

Oddly I don't see the SSL property in the UI even though this was merged this morning? I cloned the repo, and redownloaded the launcher, post merge.

![image](https://github.com/Canner/WrenAI/assets/130578303/307c5071-f8eb-4bf6-8ecb-dff9a56a1270)

**Expected behavior**
Establish connection to the db :)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise version 22H2 OS Build 22621.3296
 - Browser: Firefox 126.0, Chrome 124.0.6367.203, Chrome 124.0.6367.208, Edge 124.0.2478.97 

**WrenAI Information**
- Version: 0.3.2

**Additional context**
This is a postgresql database version 15.6 that lives in Azure.  The database is on a private network accessed via vpn.  I've tested the access with vpn on and off.  I also created a test database on public network and encountered the same "Failed to Connect" error message.

**Comment by wwwy3y3** [comment]
@andre-scheinwald thanks for reporting this issue.

If this is an SSL connection issue, we already fixed this issue and will release it in our next version (will probably be released these few days). You could try it again when we release it.

PR here for your information -> https://github.com/Canner/WrenAI/pull/255

**Comment by wwwy3y3** [comment]
hi @andre-scheinwald at our latest release (https://github.com/Canner/WrenAI/releases/tag/0.3.3), we've supported SSL option in PostgreSQL.

You may upgrade by re-running the installation and checking if it fixes your issue.

**Comment by andre-scheinwald** [comment]
@wwwy3y3 I must have jumped the gun yesterday morning when I saw PR [#255](https://github.com/Canner/WrenAI/pull/255) was merged and tried testing it out.  Now that I'm on v 0.3.3 it works! Thanks.

**Comment by wwwy3y3** [comment]
@andre-scheinwald Nice! Glad to hear that.

You could always ask us more questions, or provide us any feedback on the product in our discord -> https://discord.com/invite/5DvshJqG8Z.
