### ISSUE TITLE
Postgres SSL Issue

### ISSUE THREAD

**Issue by agalewsky-pnn** [Canner/WrenAI#296]
We are using a managed Postgres from Digital Ocean.  It requires SSL to connect.  However we get this error:

[2024-05-21T16:35:48.463] [ERROR] PostgresConnector - Error connecting to Postgres: Error: self signed certificate in certificate chain

How can we force wrenai to ignore the self signed cert.

**Comment by wwwy3y3** [comment]
Hi @agalewsky-pnn we're investigating this issue. Thanks for reporting.

**Comment by agalewsky-pnn** [comment]
Thank you very much. Digital Ocean requires ssl but dosnt have a way to
sert it..   they are much less responsicr the you guys are



Andrew Galewsky
*Chief Technology Officer, SalesCrush*

512-422-8290  |  www.salescrush.com  <http://www.salescrush.com/> |
***@***.***

"Onward through the fog."  – Oat Willie of Austin

**Comment by wwwy3y3** [comment]
Hi @agalewsky-pnn this bug has been fixed at #302. We tested with a PostgreSQL provisioned on DigitalOcean and it works well.

This fix will be included in our next release (v0.3.5), which will be released next week.

Stay tuned for our announcement in discord 😎.

**Comment by agalewsky-pnn** [comment]
Wow - that's what I call service with a smile!  Is there a way I can try it
out today before formal release?

Andrew Galewsky
*Chief Technology Officer, SalesCrush*

512-422-8290  |  www.salescrush.com  <http://www.salescrush.com/> |
***@***.***

"Onward through the fog."  – Oat Willie of Austin

**Comment by wwwy3y3** [comment]
@agalewsky-pnn Well, building the code yourself would probably take too much effort. I suggest you wait for a a few more days 😎

I'll let you know if we release earlier.

**Comment by agalewsky-pnn** [comment]
👍🏼

Andrew Galewsky
*Chief Technology Officer, SalesCrush*

512-422-8290  |  www.salescrush.com  <http://www.salescrush.com/> |
***@***.***

"Onward through the fog."  – Oat Willie of Austin

**Comment by agalewsky-pnn** [comment]
William -

I don't mean to be a pill :) but do we have feeling when the new build will
drop with the it fix in it?    I don't mind building it myself if there is
a bit of lunch instructions on how to get started...

Andrew Galewsky
*Chief Technology Officer, SalesCrush*

512-422-8290  |  www.salescrush.com  <http://www.salescrush.com/> |
***@***.***

"Onward through the fog."  – Oat Willie of Austin

**Comment by wwwy3y3** [comment]
hi @agalewsky-pnn , no problem.

We released a candidate version yesterday: https://github.com/Canner/WrenAI/releases/tag/0.3.5-rc.1 . We'll make an official release later today.

Meanwhile, you could give this version a try by running installation of this specific version:
```sh
curl -L https://github.com/Canner/WrenAI/releases/download/0.3.5-rc.1/wren-launcher-darwin.tar.gz | tar -xz && ./wren-launcher-darwin
```

**Comment by agalewsky-pnn** [comment]
I snagged the release canadate alresy and it runs great.  You guys are good
at this!

**Comment by wwwy3y3** [comment]
`0.3.5` released: https://github.com/Canner/WrenAI/releases/tag/0.3.5

Issue fixed in this official release.
