### ISSUE TITLE
400 Bad Request when asking WrenAI

### ISSUE THREAD

**Issue by TempoShaman** [Canner/WrenAI#304]
**Describe the bug**
After successful installation of WrenAI and using its UI, I get 400 Bad Request error for every input, either using preformatted questions or my own typed question.

**To Reproduce**
1. Go to UI
2. Click on preformatted question or type in question
3. See error

**Expected behavior**
No 400 Bad Request

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**WrenAI Information**
- Version: 0.3.4
![image](https://github.com/Canner/WrenAI/assets/80389825/327cd4db-00db-4d9d-bcc0-d717f2d4d8a6)
![image](https://github.com/Canner/WrenAI/assets/80389825/61815151-964e-4eb7-8951-d3bfb39f09ef)

Update 1: I tried Chrome browser with same error.

**Comment by TempoShaman** [comment]
For some reason it started working after I moved around blocks in modeling tab for NBA dataset.

**Comment by wwwy3y3** [comment]
cc @cyyeh , you could take a look if it rings a bell on issues you saw before.
