### ISSUE TITLE
PostgreSQL connection in case CA certificate needs to be uploaded (PostgreSQL is hosted on DigitalOcean in my case)

### ISSUE THREAD

**Issue by tihomir-lolic** [Canner/WrenAI#311]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cyyeh** [comment]
Hi! @tihomir-lolic Is this the same issue you are facing? https://github.com/Canner/WrenAI/issues/296

If so, we will deliver the solution in our next release!

**Comment by wwwy3y3** [comment]
@tihomir-lolic issue fixed at [0.3.5](https://github.com/Canner/WrenAI/releases/tag/0.3.5).

Could you re-install WrenAI with the latest version and try again?

Thanks

**Comment by wwwy3y3** [comment]
Closing this PR due to inactivity and the issue confirmed fixed.
