### ISSUE TITLE
Every reqeust on Home display error toast message

### ISSUE THREAD

**Issue by tihomir-lolic** [Canner/WrenAI#312]
**Describe the bug**
Docker log for every request

[2024-05-23T15:25:55.487] [DEBUG] WrenAIAdaptor - Got error when asking wren AI: Request failed with status code 400, detail: [{'type': 'string_type', 'loc': ('body', 'id'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.7/v/string_type'}]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**WrenAI Information**
- Version: [e.g, 0.1.0]

**Additional context**

**Comment by onlyjackfrost** [comment]
Can you provide your OS and WrenAI version?

**Comment by wwwy3y3** [comment]
For people who come across this issue, please take a look at this discussion thread on Discord -> https://discord.com/channels/1227143286951514152/1243764365887537162.

> We’ve encountered several users run into this issue, this discussion aims to clarify several possible ways to conquer the issue.
> 
> Please make sure the model is deployed successfully by going to the modeling page, there should be a "synced" message shown on the top right of the page. If it's not showing "synced", please click the deploy button. After the model is deployed successfully, you can start to ask questions.
> Please make sure your OpenAI api key is not under free plan, and you save some credits to your api key.
> 
> If you still encounter the issue despite of the above methods, please tell us here or raise an issue on GitHub. Thank you! 
> 

Closing this issue for now. Feel free to comment if you saw same error message thrown, but you think not because of OpenAI API key problem.
