### ISSUE TITLE
Azure OpenAI integration

### ISSUE THREAD

**Issue by TempoShaman** [Canner/WrenAI#323]
**Is your feature request related to a problem? Please describe.**
I can't use Azure OpenAI api-key.

**Describe the solution you'd like**
It would be nice to have option to use Azure OpenAI api-key for working with Wren.ai since this is main platform where I would like to use your solution.

**Describe alternatives you've considered**
One alternative can be using Azure OpenAI integration provided with Langchain but I am not certain that it would not cause any further issues. I have not tried it yet.

**Comment by cyyeh** [comment]
@TempoShaman  Thanks for reaching out! We have provided a document demonstrating how to add your preferred LLM or Document Store. Please check out this guide: https://docs.getwren.ai/installation/custom_llm. We are using Haystack underneath, and it already support Azure OpenAI. I think you can integrate it within 30 minutes.

https://docs.haystack.deepset.ai/docs/azureopenaigenerator

Feel free to ask me any questions!

**Comment by cyyeh** [comment]
@TempoShaman after this PR is merged, you can start using Azure OpenAI I think :)
https://github.com/Canner/WrenAI/pull/390

**Comment by puneet1389** [comment]
@cyyeh  firstly thanks for this solution, i was trying to explore this but i got stuck in the api key step, it is still asking for Open AI key whereas i want to add azure open AI keys. how can i proceed with this  problem?

**Comment by cyyeh** [comment]
@puneet1389 thanks for reaching out! We haven't added to our launcher yet. We'll write documentation for it later, thank you.

**Comment by cyyeh** [comment]
All, we now support using Azure OpenAI, Ollama, and OpenAI API-compatible LLMs now with the latest release: https://github.com/Canner/WrenAI/releases/tag/0.6.0

Setups on how to run Wren AI using custom LLMs: https://docs.getwren.ai/installation/custom_llm#running-wren-ai-with-your-custom-llm-or-document-store

Currently, there is one obvious limitation for custom LLMs: you need to use the same provder(such as OpenAI, or Ollama) for LLM and embedding model. We'll fix that and release a new version soon. Stay tuned 🙂

I'll close this issue as completed now.
