### ISSUE TITLE
Change OpenAI URL

### ISSUE THREAD

**Issue by mobguang** [Canner/WrenAI#330]
**Is your feature request related to a problem? Please describe.**
How to change OpenAI URL when WrenAI start up? 

Can I change the corresponding url when I set OpenAI key?
![image](https://github.com/Canner/WrenAI/assets/519028/129e9ecc-1da1-4be3-a17e-9fbf227d6e95)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cyyeh** [comment]
@mobguang Hi, it seems that u would like to use LLMs other than OpenAI's? What LLM would u like to use instead?

**Comment by mobguang** [comment]
Thanks

**Comment by cyyeh** [comment]
all, the ollama has been integrated in this branch, also you can use openai api compatible llm: `chore/ai-service/update-env`
we'll merge this branch to the main branch in the near future and update the documentation
as of now, I'll delete the original ollama branch
Thank you all for your patience

related pr: https://github.com/Canner/WrenAI/pull/376

**Comment by cyyeh** [comment]
All, we now support using Ollama, Azure OpenAI, OpenAI API-compatible LLMs now with the latest release: https://github.com/Canner/WrenAI/releases/tag/0.6.0

Setups on how to run Wren AI using custom LLMs: https://docs.getwren.ai/installation/custom_llm#running-wren-ai-with-your-custom-llm-or-document-store

Currently, there is one obvious limitation for custom LLMs: you need to use the same provder(such as OpenAI, or Ollama) for LLM and embedding model. We'll fix that and release a new version soon. Stay tuned 🙂

I'll close this issue as completed now.

**Comment by mobguang** [comment]
@cyyeh 
Thanks for the good news!

**Comment by Namec999** [comment]
Currently trying to use Groq as Open Ai compatible API provider

i am following the docs, but i think that i am missing something

can you show me the way to achieve this
