### ISSUE TITLE
When do you plan to implement an API for creating questions and receiving answers?

### ISSUE THREAD

**Issue by ikasymov** [Canner/WrenAI#391]
I want to implement my own chat in my product and use your API for interaction. Becayse WrenAI chat has unnecessary things that I would not want to see in my product. 
For my chat, all that is enough is the opportunity to ask a question and get a ready-made result in the form of rows and columns.

**Comment by wwwy3y3** [comment]
@ikasymov , we do have APIs you can directly call. We just haven't officially public our API doc at this point. 

I have described how our API works on our discord here: https://discord.com/channels/1227143286951514152/1249992463977021511

**Comment by ikasymov** [comment]
@wwwy3y3 could you please give the invite link to your discord channel? I can't see the API via that discord link, it probably has some permissions in channel

**Comment by wwwy3y3** [comment]
Hi @ikasymov no problem. https://discord.gg/5DvshJqG8Z
