### ISSUE TITLE
Table is not getting selected after searching for second time

### ISSUE THREAD

**Issue by himanshu634** [Canner/WrenAI#396]
**I was trying to select multiple tables from the search input box. I selected one table and then searched for another table and tried to select it but the first one was getting deselected.**

**To Reproduce**
1. Connect To DB.
2. Select the table.
3. Select another table after searching it.
4. The first one will get deselected.

**Expected behavior**
Both tables should be selected.

**Screenrecording**
[Video is here.](https://github.com/Canner/WrenAI/assets/61757460/a4d39fea-9ff2-4f92-a3e8-2da7b60ac6f7)

**Comment by andreashimin** [comment]
Thank you for reporting this issue.

The first table got deselected because the search input filters out the selected table. For now, you will need to clear the search input to restore the selected table before submitting.

I will discuss this problem with the team to find a fix.

**Comment by andreashimin** [comment]
Sure, your contribution would be very welcome, I can help you review the PR.
