### ISSUE TITLE
Timestamp showing unformatted value when previewing data

### ISSUE THREAD

**Issue by wwwy3y3** [Canner/WrenAI#434]
**Describe the bug**
Timestamp showing unformatted value when previewing data

**To Reproduce**
1. Ask basic "show me orders" questions that will query date/timestamp column
2. See values in date/timestamp column

**Expected behavior**
Values should be formatted. Maybe we should give LLM instructions to format date/timestamp by default ?

**Screenshots**
![Screenshot 2024-06-20 at 5 51 46 PM](https://github.com/Canner/WrenAI/assets/1208829/cd9411e1-fc2c-4959-82b3-4c0e3144dbf4)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome

**WrenAI Information**
- Version: 0.5.0

**Comment by ovachiever** [comment]
Seeing the same issue. I can ask it to convert from epoch time and it typically does, but users won't know to do this.

**Comment by cyyeh** [comment]
issue fixed
