### ISSUE TITLE
Installation of wrenAI Failed

### ISSUE THREAD

**Issue by Karissssa** [Canner/WrenAI#437]
**Describe the bug**
After following the steps and entering the OpenAI Key, the process reaches "UI Service is ready" and then shows a Timeout.

**To Reproduce**
1. Run `curl -L https://github.com/Canner/WrenAI/releases/latest/download/wren-launcher-darwin.tar.gz | tar -xz && ./wren-launcher-darwin` in terminal
2. input OpenAI API key
3. Select `gpt-3.5-turbo`
4. See error: Timeout

**Expected behavior**
See the success message for wrenAI installation or view the interface at localhost:3000.

**Screenshots**
<img width="1364" alt="image" src="https://github.com/Canner/WrenAI/assets/107385640/617e65d7-5b53-41c5-b345-d3a3416a3acd">

**Desktop (please complete the following information):**
 - OS: macOS12.7.5
 - Browser: chrome

**WrenAI Information**
- Version: wren-ui:0.8.0

**Comment by cyyeh** [comment]
can you give us container logs by entering this command in the terminal?

```
docker logs wrenai-wren-ui-1 >& wren-ui.log && \
docker logs wrenai-wren-ai-service-1 >& wren-ai-service.log && \
docker logs wrenai-wren-engine-1 >& wren-engine.log
```

**Comment by Karissssa** [comment]
hi @cyyeh 

I enter the command in the terminal and get these three .log files.
[wren-engine.log](https://github.com/user-attachments/files/15949361/wren-engine.log)
[wren-ai-service.log](https://github.com/user-attachments/files/15949362/wren-ai-service.log)
[wren-ui.log](https://github.com/user-attachments/files/15949363/wren-ui.log)

**Comment by cyyeh** [comment]
hmm, it's weird that I saw the word "killed" from the wren-ai-service.log. It seems that the process is being killed.

**Comment by Karissssa** [comment]
hi @cyyeh Is there any new information?

**Comment by cyyeh** [comment]
@Karissssa can you try earlier version of WrenAI? Currently there is still not enough information for me to help u solve the issue

**Comment by cyyeh** [comment]
@Karissssa We have the new release here: https://github.com/Canner/WrenAI/releases/tag/0.6.0

Could you try the latest version and see if it helps? Thank you

**Comment by Karissssa** [comment]
hi @cyyeh How do i specify the latest version using `curl -L https://github.com/Canner/WrenAI/releases/latest/download/wren-launcher-darwin.tar.gz | tar -xz && ./wren-launcher-darwin`?

**Comment by cyyeh** [comment]
> hi @cyyeh How do i specify the latest version using `curl -L https://github.com/Canner/WrenAI/releases/latest/download/wren-launcher-darwin.tar.gz | tar -xz && ./wren-launcher-darwin`?

The script you gave would install the latest version.

**Comment by cyyeh** [comment]
> hi @cyyeh Still the same timeout, and these three .log files. <img alt="image" width="1340" src="https://private-user-images.githubusercontent.com/107385640/344580098-eee46a5f-d1c5-46f7-ba86-394b0a2cf54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjUxODYsIm5iZiI6MTcxOTgyNDg4NiwicGF0aCI6Ii8xMDczODU2NDAvMzQ0NTgwMDk4LWVlZTQ2YTVmLWQxYzUtNDZmNy1iYTg2LTM5NGIwYTJjZjU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwOTA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmI0ZTc3NjFlZDRiYTEyMGQ4YjQxYzZmZjUzODc1NTE3N2IxNmQyNDNiNTI5NmUxY2I4NmJmOTk0MjU0NmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FWZibqu6EEs6z6Mqt9Za83nuRtYYsfNJWscVZYXmv1Q"> [wren-ai-service.log](https://github.com/user-attachments/files/16049271/wren-ai-service.log) [wren-engine.log](https://github.com/user-attachments/files/16049274/wren-engine.log) [wren-ui.log](https://github.com/user-attachments/files/16049277/wren-ui.log)

@Karissssa from the log mentioning the keyword "killed", it seems that one of the processes of Wren AI is being kill while it's being started. Sorry, now we don't exactly know what happened. Or do you have other computers to try or are you running other applications that might cause this?

**Comment by cyyeh** [comment]
@Karissssa could I close the issue now?

**Comment by gzcharles** [comment]
![未命名1724256343](https://github.com/user-attachments/assets/2c9e5c49-5eea-4ea2-bcee-b1e5e0beb50f)
how to solve this problem?

**Comment by cyyeh** [comment]
you could rerun the launcher again, and welcome to use the latest version
