### ISSUE TITLE
No relevant SQL found for the given query. Please check your query and try again.

### ISSUE THREAD

**Issue by suiquantong** [Canner/WrenAI#446]
**Describe the bug**
  No relevant SQL
  No relevant SQL found for the given query. Please check your query and try again.
**To Reproduce**
1. 连接数据库，设置数据库的注释
2. 点击发送问题
3. 

**Expected behavior**
我请求了接口，看到数据也有返回，但是最后页面并没有显示数据

**Screenshots**

**Container Logs **

```
docker logs wrenai-wren-ui-1 >& wren-ui.log && \
docker logs wrenai-wren-ai-service-1 >& wren-ai-service.log && \
docker logs wrenai-wren-engine-1 >& wren-engine.log
docker logs wrenai-ibis-server-1 >& wrenai-ibis-server-1.log
```

**Desktop (please complete the following information):**
 - OS: Linux Ubutun 22.04
 - Browser chrome

**Wren AI Information**
- Version: [0.5.0]
- 
[wren-engine.log](https://github.com/user-attachments/files/16007505/wren-engine.log)
[wren-ai-service.log](https://github.com/user-attachments/files/16007506/wren-ai-service.log)
[wrenai-ibis-server-1.log](https://github.com/user-attachments/files/16007507/wrenai-ibis-server-1.log)
[wren-ui.log](https://github.com/user-attachments/files/16007508/wren-ui.log)

**Additional context**

**Comment by cyyeh** [comment]
@suiquantong sorry, content of the logs is empty, it seems that you are not using launcher to start WrenAI, right? So, the container names are wrong.

**Comment by suiquantong** [comment]
我想知道 我如何在启动前更改我的 openai 的地址&nbsp;&nbsp;


〆落花ァ笑彷徨ㄟ
***@***.***



&nbsp;

**Comment by cyyeh** [comment]
@suiquantong it's good timing haha. we'll release this next week. I'll provide documentation here.

**Comment by suiquantong** [comment]
还有个问题，我再重启后容器后 会重新加载/root/.wrenai/.env 里面的配置参数嘛
夏笙
***@***.***
---- Replied Message ----
FromChih-Yu ***@***.***>Date6/27/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [Canner/WrenAI] No relevant SQL found for the given query. Please check your query and try again. (Issue #446)
@suiquantong it's good timing haha. we'll release this next week. I'll provide documentation here.

**Comment by wwwy3y3** [comment]
> 还有个问题，我再重启后容器后 会重新加载/root/.wrenai/.env 里面的配置参数嘛

I don't think restarting container will reload env.

You'll have to re-run the launcher again. The launcher will do a `docker-compose up` again, which should recreate the containers with the new environment variables.

**Comment by suiquantong** [comment]
每次 执行./wren-launcher-linux 都会执行如下操作 会覆盖我的修改
Downloading docker-compose file to /root/.wrenai/docker-compose.yaml 
Downloading env file to /root/.wrenai/.env.example 
我不想让他覆盖的我配置
夏笙
***@***.***
---- Replied Message ----
Fromwilliam ***@***.***>Date6/27/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [Canner/WrenAI] No relevant SQL found for the given query. Please check your query and try again. (Issue #446)
还有个问题，我再重启后容器后 会重新加载/root/.wrenai/.env 里面的配置参数嘛
I don't think restarting container will reload env.
You'll have to re-run the launcher again. The launcher will do a docker-compose up again, which should recreate the containers with the new environment variables.

**Comment by suiquantong** [comment]
[wrenai-ibis-server-1.log](https://github.com/user-attachments/files/16008263/wrenai-ibis-server-1.log)
[wren-ui.log](https://github.com/user-attachments/files/16008264/wren-ui.log)
[wren-engine.log](https://github.com/user-attachments/files/16008265/wren-engine.log)
[wren-ai-service.log](https://github.com/user-attachments/files/16008266/wren-ai-service.log)

**Comment by wwwy3y3** [comment]
@suiquantong I see. May I know what adjustments you made to the env file ?

Maybe you could start Wren AI without launcher. Just cd to `~/.wrenai` and run `docker-compose up`. This way you could control the env file content yourself and reload env by running `docker-compose up` again.

Check StackOverflow here for reference: https://stackoverflow.com/a/42150882/1191953
