### ISSUE TITLE
Clickhouse support

### ISSUE THREAD

**Issue by Namec999** [Canner/WrenAI#453]
Hello Team,

Is there any schedule for clickhouse support and also Ms Sql

Best

**Comment by wwwy3y3** [comment]
hi @Namec999,

Yes, MSSQL support is coming in the next version, which will be released soon.

For Clickhouse support, it will be scheduled after the next release.

Additionally, you could check community feedbacks on database support here: https://github.com/Canner/WrenAI/discussions/327. We'll also update the current status in the comments.
