### ISSUE TITLE
Groq API implementation

### ISSUE THREAD

**Issue by Namec999** [Canner/WrenAI#475]
Currently trying to use Groq as Open Ai compatible API provider

i am following the docs, but i think that i am missing something

can you show me the way to achieve this

**Comment by cyyeh** [comment]
@Namec999 hi, thanks for reaching out! First of all, it seems that Groq doesn't provide embedding models right? If so, currently Wren AI only supports embedding models and LLM using the same provider. We'll fix this in the next release.
