### ISSUE TITLE
Issues while clicking on deploy Option on Wren AI UI using Azure LLM

### ISSUE THREAD

**Issue by puneet1389** [Canner/WrenAI#485]
**Describe the bug**
Error Observed while clicking on **Deploy** option on under modelling section of Wren AI UI.
LLM used: Azure Open AI GPT-4o

**To Reproduce**
Steps to reproduce the behavior:[Uploading logs.docx…]()
**Additional context**

**Comment by cyyeh** [comment]
[logs.docx](https://github.com/user-attachments/files/16112859/logs.docx)

**Comment by cyyeh** [comment]
issue fixed
