### ISSUE TITLE
Installation should stop when exiting the launcher

### ISSUE THREAD

**Issue by chilijung** [Canner/WrenAI#509]
**Describe the bug**
as title

**To Reproduce**
1. start launcher
2. when selecting `openai` or `others`
3. hit ctrl + c to exit
4. it continues to install

**Expected behavior**
should exit the command

**Screenshots**
![image](https://github.com/user-attachments/assets/7a6c7cba-9f77-4560-85cc-162d634f2bee)

**Comment by Prototype4988** [comment]
Hi Team, I would like to look into this issue. Could you assign it to me

**Comment by chilijung** [comment]
@Prototype4988 Here you go!

**Comment by Prototype4988** [comment]
Hi Team, I have done the fix attaching the screenshot from console below

![image](https://github.com/user-attachments/assets/062c50be-11fa-40be-b24f-a9de97c6e768)

**Comment by Prototype4988** [comment]
I have added the below code snippet in Launch() function 

`done := make(chan os.Signal, 1)
	
	signal.Notify(done, os.Interrupt)

    // Fire off a goroutine to loop until that channel receives a signal.
    // When a signal is received simply exit the program
    go func() {
        for _ = range done {
            os.Exit(0)
        }
    }()`

**Comment by Prototype4988** [comment]
Let me know what you think of this approach

**Comment by chilijung** [comment]
PR is merged!
