### ISSUE TITLE
Support of Teradata and oracle by WrenAI

### ISSUE THREAD

**Issue by sharathchandran2001** [Canner/WrenAI#526]
Please let us know your plans about supporting Teradata and oracle.  Appreciate your response.
Is there any custom connectors or logic would support Teradata

**Comment by wwwy3y3** [comment]
Hi @sharathchandran2001 , you could upvote the databases you think Wren AI should support here: https://github.com/Canner/WrenAI/discussions/327

> Is there any custom connectors or logic would support Teradata

As for the instructions to customize or contribute a connector, we're working on that. Will update here once we update the documents.

**Comment by wwwy3y3** [comment]
Closing this.
Oracle -> https://github.com/Canner/WrenAI/issues/710
Teradata -> https://github.com/Canner/WrenAI/discussions/327#discussioncomment-10068448
