### ISSUE TITLE
wren-ai-service api doc 

### ISSUE THREAD

**Issue by Namec999** [Canner/WrenAI#533]
hello all

looking through the doc, but cant find any documentation for using the wren-service-api, using my own UI

best

**Comment by wwwy3y3** [comment]
Hi @Namec999 We haven't officially released our API documentation at this point. Please check this discord thread: [How WrenAI API works](https://discord.com/channels/1227143286951514152/1249992463977021511) to understand how Wren AI API works.

**Comment by Gautam-J** [comment]
@Namec999 you can find the swagger API docs by going to your backend port.
[Link](https://github.com/Canner/WrenAI/tree/main/wren-ai-service#:~:text=API%20Documentation%3A%20http%3A//WREN_AI_SERVICE_HOST%3AWREN_AI_SERVICE_PORT%20(default%3A%20http%3A//localhost%3A5556)) to reference.
