### ISSUE TITLE
BigQuery metadata ingestion

### ISSUE THREAD

**Issue by damon09273** [Canner/WrenAI#576]
**Is your feature request related to a problem? Please describe.
When I need to retrieve the table description from BigQuery, I find that the current WrenAI interface does not provide this functionality directly. I hope the existing metadata can be synchronized to WrenAI to help the AI better understand my data and provide more accurate and valuable responses.

**Describe the solution you'd like
I want WrenAI to add a feature that allows users to retrieve and view table descriptions from BigQuery easily. This feature should be integrated into the table inspection tools, enabling users to see the table description alongside the schema and other metadata.

**Describe alternatives you've considered
I have considered manually using the Google Cloud Console to view table descriptions in BigQuery, but this method is time-consuming and inconvenient. Additionally, I have considered using API calls to fetch the table descriptions, but this requires extra scripting and is not user-friendly for all team members.

**Additional context
Viewing table descriptions directly within WrenAI would greatly enhance the efficiency of our data analysis. This feature would be especially important for teams dealing with complex datasets and relying on detailed schema documentation.

**Comment by wwwy3y3** [comment]
Hi @damon09273 , thank you for sharing your feedback with us.

Maybe the table descriptions you mentioned could be queried from INFORMATION_SCHEMA and integrated into our internal catalog. For instance, we can retrieve table descriptions using a SQL query like this:
```sql
SELECT 
  table_name, 
  table_type, 
  description 
FROM 
  `project_id.dataset_id.INFORMATION_SCHEMA.TABLES`
WHERE 
  table_name = 'your_table_name';
```

We’ll discuss this feature request internally. Thanks again!

**Comment by damon09273** [comment]
> Hi @damon09273 , thank you for sharing your feedback with us.
> 
> 
> 
> Maybe the table descriptions you mentioned could be queried from INFORMATION_SCHEMA and integrated into our semantic layer. For instance, we can retrieve table descriptions using a SQL query like this:
> 
> ```sql
> 
> SELECT 
> 
>   table_name, 
> 
>   table_type, 
> 
>   description 
> 
> FROM 
> 
>   `project_id.dataset_id.INFORMATION_SCHEMA.TABLES`
> 
> WHERE 
> 
>   table_name = 'your_table_name';
> 
> ```
> 
> 
> 
> We’ll discuss this feature request internally. Thanks again!

Fantastic, yes, this was what I meant.

**Comment by onlyjackfrost** [comment]
closing due to duplicated issue https://github.com/Canner/WrenAI/issues/671

**Comment by wwwy3y3** [comment]
It's now supported in Wren AI, starting in version 0.9.0 (https://github.com/Canner/WrenAI/releases/tag/0.9.0)
