### ISSUE TITLE
Unknown dialect 'mssql'. Did you mean mysql?

### ISSUE THREAD

**Issue by ontirius** [Canner/WrenAI#581]
**Describe the bug**
WrenAI response is always:  "No relevant SQL found for the given query"
Also with simple questions like: "Lists all row that you find inside table <name of table>"  the strange things is that inside logs of enging I'm able to find a correct query! So seems that the AI works fine, but inside ibis-server logs there is that error:  "Unknown dialect 'mssql'. Did you mean mysql?"

**To Reproduce**
Configure WrenAI to works with MS SQL and fireworks.ai as LLM, and make a question

**Expected behavior**
We expect a clear response that contains data from MS SQL

**Screenshots**
![image](https://github.com/user-attachments/assets/a56a0cf8-b5a6-4226-8f4a-e8bf68bf74ed)

**Desktop (please complete the following information):**
- OS: Win10
- Browser chrome

**Wren AI Information**
- Version: latest
- LLM_PROVIDER= openai_llm
- GENERATION_MODEL= accounts/fireworks/models/llama-v3p1-405b-instruct

Many thanks!

**Comment by cyyeh** [comment]
Issue confirmed, and we will fix it asap. Thank you!

**Comment by grieve54706** [comment]
@wwwy3y3, please close this fixed issue.
