### ISSUE TITLE
Unable to deploy model with embedding model text-embedding-ada-002

### ISSUE THREAD

**Issue by raina0990** [Canner/WrenAI#583]
**Describe the bug**

After successful start of the Wren AI, when I try deoloy model  for Azure Open AI setup. I get below error: 
  openai.BadRequestError: **Error code: 400 - {'error': {'message': 'This model does not support specifying dimensions.', 'type': 'invalid_request_error', 'param': None, 'code': None}}**
-------------------------------------------------------------------
Oh no an error! Need help with Hamilton?
Join our slack and ask for help! https://join.slack.com/t/hamilton-opensource/shared_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg
-------------------------------------------------------------------
2024-08-02 21:53:15,557 - **wren-ai-service - ERROR - ask pipeline - Failed to prepare semantics: Error code: 400 - {'error': {'message': 'This model does not support specifying dimensions.', 'type': 'invalid_request_error', 'param': None, 'code': None}} (indexing.py:60)**

**To Reproduce**
1. set up .env.ai for azure_open_ai
2. Set embedding model as follows: 
EMBEDDING_MODEL=text-embedding-ada-002
EMBEDDING_MODEL_DIMENSION=1536

**Expected behavior**
Model should be deployed. We should get 'synced' message in the UI

**Wren AI Information**
- Version: 0.7.3
- LLM_PROVIDER= azure_openai_llm
- GENERATION_MODEL= gpt-4o

**Comment by cyyeh** [comment]
@raina0990 this bug is already fixed with this PR(), and will be released in the next official release. stay tuned :)

https://github.com/Canner/WrenAI/pull/579
