### ISSUE TITLE
Mssql database connection 

### ISSUE THREAD

**Issue by johnfelipe** [Canner/WrenAI#586]
Is possible connect with Mssql database?

**Comment by cyyeh** [comment]
@johnfelipe it's already supported in Wren AI. please refer to the docs for connection setup, thanks!

https://docs.getwren.ai/guide/connect/sqlserver

**Comment by cyyeh** [comment]
Also there is an issue using mssql, we will fix it asap

https://github.com/Canner/WrenAI/issues/581

**Comment by johnfelipe** [comment]
steps to perform these actions in a Windows environment using Docker and PowerShell. Here's how you can do it:

1. Turn off all WrenAI-related containers:
   Open PowerShell and run:
   ```powershell
   docker stop $(docker ps -q --filter "name=wrenai")
   ```

2. Open PowerShell:
   You can do this by pressing Win + X and selecting "Windows PowerShell" or "Windows PowerShell (Admin)".

3. Navigate to the WrenAI directory:
   In Windows, the ~/.wrenai directory is typically located in your user folder. Run:
   ```powershell
   cd $env:USERPROFILE\.wrenai
   ```

4. Rename .env to .env.txt:
   ```powershell
   Rename-Item .env .env.txt
   ```

5. Open .env.txt in Notepad:
   ```powershell
   notepad .env.txt
   ```

6. In Notepad, find the line with IBIS_SERVER_VERSION and change its value to msodbc-driver. Save the file and close Notepad.

7. Rename .env.txt back to .env:
   ```powershell
   Rename-Item .env.txt .env
   ```

8. Run docker-compose with the updated .env file:
   ```powershell
   docker-compose --env-file .env up -d
   ```

These steps should accomplish the tasks you've outlined in a Windows environment. Make sure you have the necessary permissions to modify files in the .wrenai directory and to run Docker commands.
