### ISSUE TITLE
multilingual input and output

### ISSUE THREAD

**Issue by johnfelipe** [Canner/WrenAI#588]
if prompt is in spanish 
output can be in spanish?
i can contribute if you have strings in any type of format

![SNAG-0563](https://github.com/user-attachments/assets/aeec9f67-55f0-47b6-b462-35b5cb8219ae)

**Comment by cyyeh** [comment]
thanks for reaching out! I need to discuss with the team to think about better design for functionalities added by community. will reply to u asap

**Comment by johnfelipe** [comment]
hi dear, me again, this is possible?
input spanish
output spanish

**Comment by cyyeh** [comment]
already supported, so I'll close the issue
