### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by LZZJ** [Canner/WrenAI#597]
Is there any developer documentation for this project? 
I want to learn about this project, but I can't find the developer documentation.

**Comment by cyyeh** [comment]
@LZZJ thanks for reaching out! now we have READMEs for each sub-system and documentation website for Wren AI. The information seems incomplete to you. I am wondering what is missing from your standpoint. We thank you for your input!

**Comment by LZZJ** [comment]
Thank you !
