### ISSUE TITLE
Ibis server error '42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]

### ISSUE THREAD

**Issue by johnfelipe** [Canner/WrenAI#606]
![SNAG-0603](https://github.com/user-attachments/assets/a2217508-229b-4b96-ae06-56de5227305e)

```powershell
docker logs wrenai-wren-ui-1 *> wrenai-wren-ui.log; `
docker logs wrenai-wren-ai-service-1 *> wrenai-wren-ai-service.log; `
docker logs wrenai-wren-engine-1 *> wrenai-wren-engine.log; `
docker logs wrenai-ibis-server-1 *> wrenai-ibis-server.log
```

Here's what changed:

1. Replaced `>&` with `*>` for redirecting both standard output and standard error.
2. Replaced `&&` with `;` to separate commands.
3. Used the PowerShell line continuation character `` ` `` (backtick) at the end of each line except the last one.

If you want to append to the log files instead of overwriting them, you can use `*>>` instead of `*>`:

```powershell
docker logs wrenai-wren-ui-1 *>> wrenai-wren-ui.log; `
docker logs wrenai-wren-ai-service-1 *>> wrenai-wren-ai-service.log; `
docker logs wrenai-wren-engine-1 *>> wrenai-wren-engine.log; `
docker logs wrenai-ibis-server-1 *>> wrenai-ibis-server.log
```

here is logs

[wrenai-wren-ui.log](https://github.com/user-attachments/files/16624446/wrenai-wren-ui.log)
[wrenai-ibis-server.log](https://github.com/user-attachments/files/16624447/wrenai-ibis-server.log)
[wrenai-wren-ai-service.log](https://github.com/user-attachments/files/16624448/wrenai-wren-ai-service.log)
[wrenai-wren-engine.log](https://github.com/user-attachments/files/16624449/wrenai-wren-engine.log)

**Comment by grieve54706** [comment]
Hi @johnfelipe,

I saw the log. It's seem different environment with your issue. The ibis-server log still use FreeTDS, not msodbc. Could you check the log is correct again?

**Comment by grieve54706** [comment]
@wwwy3y3, please close this unfollowed PR.
