### ISSUE TITLE
Installation of Wrenai fail

### ISSUE THREAD

**Issue by gzcharles** [Canner/WrenAI#617]
![未命名1724256343](https://github.com/user-attachments/assets/d06e2dba-4ee1-4d2b-91b2-3005aa7d2641)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Wren AI Information**
- Version: [e.g, 0.1.0]
- LLM_PROVIDER= # openai_llm, azure_openai_llm, ollama_llm
- GENERATION_MODEL= # gpt-3.5-turbo, llama3:70b, etc.

**Additional context**

**Comment by cyyeh** [comment]
@gzcharles Thanks for reaching out! Could you try again? I suppose there was a network issue while you were trying to download the resource from GitHub?

The resource seems available now: https://raw.githubusercontent.com/Canner/WrenAI/0.7.5/docker/docker-compose.yaml

**Comment by gzcharles** [comment]
> @gzcharles Thanks for reaching out! Could you try again? I suppose there was a network issue while you were trying to download the resource from GitHub.
> 
> The resource seems available now: https://raw.githubusercontent.com/Canner/WrenAI/0.7.5/docker/docker-compose.yaml

yep, the problem had been solved, thanks!
