### ISSUE TITLE
Running on Local

### ISSUE THREAD

**Issue by LZZJ** [Canner/WrenAI#623]
My system is Windows 10.
If I want to run this project locally with source code, which services should I run in sequence?
I initially ran WREN UI. The following error occurred.
-----------------------------------------------------------------------
D:\workspace\WrenAI\wren-ui>yarn dev
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.4
  - Local:        http://localhost:3000

 ✓ Starting...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

 ✓ Ready in 5.3s
 ○ Compiling / ...
 ✓ Compiled / in 8.5s (2203 modules)
 GET / 200 in 9631ms
 ○ Compiling /api/graphql ...
 ✓ Compiled /api/graphql in 2.8s (563 modules)
 ✓ Compiled (647 modules)
 GET /api/config 200 in 3556ms
[2024-08-27T11:20:08.099] [INFO] TELEMETRY - Telemetry not enabled.
using pg
[2024-08-27T11:20:08.225] [INFO] AskingService - Background tracker started
 ⨯ error: select * from "thread_response" - 关系 "thread_response" 不存在
    at Parser.parseErrorMessage (D:\workspace\WrenAI\wren-ui\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (D:\workspace\WrenAI\wren-ui\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (D:\workspace\WrenAI\wren-ui\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (D:\workspace\WrenAI\wren-ui\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 108,
  severity: '错误',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1395',
  routine: 'parserOpenTable',
  page: '/api/graphql'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 1010ms (2305 modules)
 POST /api/graphql 500 in 4999ms
-------------------------------------------------------------------------
Then I ran wren ai service. The following error occurred.
----------------------------------------------------------------------
(wrenai) D:\workspace\WrenAI\wren-ai-service>just test
rm -rf tools/dev/etc
error: Recipe `prepare-wren-engine` could not be run because just could not find the shell: program not found
-------------------------------------------------------------------------
Now I am learning how to run wren engine locally using source code.
Can you tell me how to quickly run this project locally using source code？

**Comment by SubrahmanyamNaidu** [comment]
If you are running with npm try to do it with yarn it is working for me 

# windows
1. SET DB_TYPE=pg
2. SET PG_URL=postgres://user:password@localhost:5432/dbname 
3. yarn migrate
4. yarn dev

Make sure you are running your docker in your background Happy coding!

**Comment by SamWang-llm** [comment]
@LZZJ @SubrahmanyamNaidu  Hi, have you run wrenai on local successfully, I followed the instruction by @SubrahmanyamNaidu but it turned out that no command dev found. Can you guys take a look, thanks a lot~


 MacBook-Air WrenAI-main % yarn migrate
yarn run v1.22.22
error Command "migrate" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(base) MacBook-Air WrenAI-main % yarn dev
yarn run v1.22.22
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
