### ISSUE TITLE
wren-launcher is incompatible with headless linux 

### ISSUE THREAD

**Issue by tikimo** [Canner/WrenAI#640]
The commands used check for Docker Desktop, which is not in my understanding a requirement.

This prevents the launcher from utilizing a headless Docker installation (Docker CLI) as it keeps looking for the docker-desktop. Docker desktop requires KVM, which is not available on all hosts.

https://github.com/Canner/WrenAI/blob/2d13dddc3c4b146ea2f3afa3b7fe723b834a0b40/wren-launcher/utils/docker.go#L97

**Comment by tikimo** [comment]
Case: 
Ubuntu 22.04 server, headless, no GUI

**Comment by tikimo** [comment]
`INFO  Checking if Docker daemon is running
 INFO  Docker daemon is not running, opening Docker Desktop
  ERROR   An error occurred: exit status 5`

**Comment by cyyeh** [comment]
@tikimo thanks for reaching out!

https://github.com/Canner/WrenAI/blob/2d13dddc3c4b146ea2f3afa3b7fe723b834a0b40/wren-launcher/utils/os.go#L57
how about changing the line to `"systemctl", "--user", "start", "docker"`?

Does that work to you?

**Comment by tikimo** [comment]
works!
