### ISSUE TITLE
Add Visualization Feature to the AI Service

### ISSUE THREAD

**Issue by Candytigers** [Canner/WrenAI#644]
The current AI service only support answers with SQL statement. It would be super helpful if there's a new feature to generate visualization with the answers. For example, it could return a bar chart as requested with a question like: Could you generate a bar chart with total quantity sold for each product?

**Comment by wwwy3y3** [comment]
That's a nice feature request @Candytigers 

Could you share more about why you think it's critical at our discussion thread here: https://github.com/Canner/WrenAI/discussions/620

Your feedbacks will help us understand your scenarios.

**Comment by cyyeh** [comment]
@Candytigers This is released now! Welcome to try it here: https://github.com/Canner/WrenAI/releases/tag/0.13.2
