### ISSUE TITLE
Get comments from the database

### ISSUE THREAD

**Issue by LZZJ** [Canner/WrenAI#655]
![image](https://github.com/user-attachments/assets/389387a2-81b4-43ad-9d32-d80bdc516f5b)
It did not obtain the table and column comments for the database here.
I hope to obtain comments directly from the database instead of manually filling them out here.
When can this feature be implemented?

**Comment by wwwy3y3** [comment]
Hi @LZZJ thanks for the feature request. 

At this point, we haven't put this in our roadmap yet, but we'd like to hear more from the community. Could you open a discussion thread here: https://github.com/Canner/WrenAI/discussions , so we could see if others have the same thoughts.

**Comment by onlyjackfrost** [comment]
closing due to duplicated issue #671

**Comment by wwwy3y3** [comment]
It's now supported in Wren AI, starting in version 0.9.0 (https://github.com/Canner/WrenAI/releases/tag/0.9.0)
