### ISSUE TITLE
How to run wrenai locally using source code without using docker #wrenai

### ISSUE THREAD

**Issue by iamsunnyyz** [Canner/WrenAI#669]
I have been trying to run the application locally, I'am able to run it with docker, but how can run without docker.

Let me know if it is possible to run with the source code #with out docker.

**Comment by wwwy3y3** [comment]
Hi @iamsunnyyz, you can start Wren AI from source code without using Docker by following the steps outlined in the [drafted contribution guide](https://github.com/Canner/WrenAI/blob/2e1642480a95b99ba96e24b456f6dd94d5a2ee1f/CONTRIBUTING.md).

This guide includes instructions for setting up the various services that WrenAI uses. If you're not familiar with the architecture of WrenAI, I recommend checking out the [overview documentation](https://docs.getwren.ai/oss/overview/how_wrenai_works), which explains how WrenAI operates and its different components.

Let me know if you need help with any specific part of the setup!

**Comment by wwwy3y3** [comment]
Contribution guide is released: https://github.com/Canner/WrenAI/blob/main/CONTRIBUTING.md

Closing this issue.
