### ISSUE TITLE
Inherit comments from DB

### ISSUE THREAD

**Issue by luca-iannelli** [Canner/WrenAI#671]
It would be useful to add the possibility that the data model inherits comments directly from the database.
For example, in my databases there are often comments for each table and also for each single column. This is for ease of maintenance.
The comments could be imported automatically into the data model (at the moment from the web interface they must be written manually) introducing more information about the semantics of the data and the relationships between tables.

**Comment by wwwy3y3** [comment]
Hi @luca-iannelli Thank you for the feedback!

This is a great idea, and we've heard similar suggestions before. Could you start a thread in the GitHub Discussions? This way, we can invite the community to join the conversation and gather more ideas or needs that we can integrate.

**Comment by endgameapp** [comment]
I also agree about this. Takin over the metadata from BigQuery would help us a lot...

**Comment by onlyjackfrost** [comment]
similar feature request https://github.com/Canner/WrenAI/issues/655

**Comment by wwwy3y3** [comment]
It's now supported in Wren AI, starting in version 0.9.0 (https://github.com/Canner/WrenAI/releases/tag/0.9.0)

**Comment by wwwy3y3** [comment]
Closing this issue
