### ISSUE TITLE
Add the `TrustServerCertificate` parameter for MS ODBC Driver

### ISSUE THREAD

**Issue by grieve54706** [Canner/WrenAI#698]
**Is your feature request related to a problem? Please describe.**
Yes, the current implementation of the MS ODBC Driver in `wren-engine` enforces server certificate validation by default. This default behavior causes connectivity issues for users who do not have server certificate validation enabled, preventing them from successfully establishing connections.

**Describe the solution you'd like**
Introduce the `TrustServerCertificate` parameter within the `connectionInfo.kwargs` JSON configuration. By setting `"TrustServerCertificate": "YES"`, users can bypass the default server certificate validation, allowing them to connect using the MS ODBC Driver without encountering validation errors. This parameter will be passed to `wren-engine`, enabling the use of the updated driver configuration.

**Describe alternatives you've considered**
- **Disabling Certificate Validation Globally:** While this would resolve the immediate connectivity issue, it compromises the security of the connection by exposing it to potential man-in-the-middle attacks.
- **Manual Configuration by Users:** Requiring users to manually adjust their driver settings to disable certificate validation adds complexity and potential for misconfiguration, leading to inconsistent user experiences.
- **Providing Detailed Documentation:** Enhancing documentation to guide users on how to disable certificate validation. However, this does not address the root cause and relies on users taking additional steps.

**Additional context**
Implementing the `TrustServerCertificate` parameter provides a flexible and secure way for users to opt-in to bypassing certificate validation when necessary. This change ensures compatibility with environments where certificate validation is not feasible, without forcing all users to disable a critical security feature. Below is an example of the JSON configuration to be passed to `wren-engine`:

```json
{
  "connectionInfo": {
    "kwargs": {
      "TrustServerCertificate": "YES"
    }
  }
}
```

This update will allow wren-engine to utilize the new driver settings seamlessly, enhancing the overall user experience and connectivity reliability.

**Comment by himanshu634** [comment]
@wwwy3y3  Can I take this?

**Comment by wwwy3y3** [comment]
@himanshu634 assigned!
