### ISSUE TITLE
The UI will briefly pop up a "No results found" message for no more than one second, then disappear and enter the state of searching for data.

### ISSUE THREAD

**Issue by fredalai** [Canner/WrenAI#699]
### Describe the bug
The UI will briefly pop up a "No results found" message for no more than one second, then disappear and enter the state of searching for data.

### To Reproduce
1. Go to **Home** page
2. Asks a question and sees the candidate's results
3. Do nothing (do not click the Close button) and directly ask questions again.
4. See the UI briefly pop up the warning - Please try again with No results found message

###  Expected behavior
Should not see that

### Screenshots
![截圖 2024-10-03 上午11 38 12](https://github.com/user-attachments/assets/2ac8d88a-3e8a-4a8a-adb0-14949c1f8690)

### Root cause
The problem occurred because the status was not cleared before submitting the question.

### Solution
Reset process state before submitting a question

**Comment by sahil9001** [comment]
Hey @wwwy3y3 , can you please assign me this issue?

**Comment by fredalai** [comment]
Hi @sahil9001 assigned!  :D
