### ISSUE TITLE
Add E2E tests for Trino Data Source

### ISSUE THREAD

**Issue by fredalai** [Canner/WrenAI#704]
## Summary 
We need contributors to help develop end-to-end (E2E) tests for the Trino data source. The goal is to cover the entire onboarding process—from connecting Trino to reaching the home page after successful data source setup.
 
## Description
The goal is to ensure the entire onboarding flow for Trino works as expected, including:
 - Connect to Trino by selecting it as a data source and filling out the connection details (e.g., host, port, username, password...etc).
 - Select all tables as data models.
 - Accept all recommended relationships if they have.
 - Successfully reach the home page after completing the setup process.

### Note:
 - You may run a Trino docker container locally and connect it.
   - local host Trino container, use: https://hub.docker.com/r/trinodb/trino
     - Default username: admin
     - no default password
 - When development is complete, please execute CLI to run the tests and include the results in your PR. Ensure that at least the test you added is included, e.g.,: `yarn test:e2e e2e/specs/connectTrino.spec.ts`

## References:
 - Use Playwright for writing the E2E tests, please refer to the [WrenAI E2E testing README](https://github.com/Canner/WrenAI/blob/main/wren-ui/e2e/README.md) to develop.
 - Feel free to explore our existing codebase, we also have shared functions and test cases in our current test suite to help you get started: [WrenAI E2E Specs](https://github.com/Canner/WrenAI/tree/main/wren-ui/e2e/specs)

**Comment by princetoday** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by fredalai** [comment]
Hi @princetoday 

Thank you for your interest in the issues! We appreciate it.

However, for the Hacktoberfest events, we will only assign one ticket to the same person at a time.

Feel free to work on multiple issues simultaneously, but we will only assign one issue to a person at a time. This means you can submit two pull requests simultaneously, but we won't assign more than one issue to you at once.

Looking forward to your contribution!

**Comment by Tryxns** [comment]
Hi @fredalai, I want to resolve this issue, may I be the assignee?

**Comment by chilijung** [comment]
@Tryxns assigned.

**Comment by Tryxns** [comment]
Hi @chilijung @fredalai , I think I'm not ready yet to resolve this issue so I'll unassign myself. Thanks for the chance given :pray:

**Comment by saai-syvendra** [comment]
Hi @fredalai!

When I selected all the tables from "tiny" Schema from the "tcph" Catalog, I got the following error message

![image](https://github.com/user-attachments/assets/acec03aa-3f56-4402-a047-4660f572f5c8)

"UNIQUE constraint failed: model_column.model_id, model_column.reference_name" with this error in the console.

Can you guide me on what this error is please

**Comment by fredalai** [comment]
@Tryxns 
It's fine.  :) Thank you for taking the time to work on this issue. If you feel ready to take on similar tasks in the future, we’d be happy to have you involved again.

**Comment by onlyjackfrost** [comment]
@saai-syvendra  Sorry about that, It's a bug on Wren Engine.
https://github.com/Canner/wren-engine/issues/833
We'll fix it ASAP. Thanks for raising this =D

**Comment by ongdisheng** [comment]
Hi @fredalai, may I work on this issue if it's still available?

**Comment by onlyjackfrost** [comment]
@saai-syvendra https://github.com/Canner/wren-engine/issues/833 had been solved. You can pull the latest Wren Engine and continue setting it up.

**Comment by onlyjackfrost** [comment]
@saai-syvendra BTW are you working on this issue or just raising the problem you encountered?

**Comment by saai-syvendra** [comment]
@onlyjackfrost alrights.. Yes, I encountered this while running the tests.. Will rerun the tests and make a PR

**Comment by ongdisheng** [comment]
@fredalai, no worries.

**Comment by ongdisheng** [comment]
@fredalai, no worries.
