### ISSUE TITLE
Add E2E tests for Human Resource sample dataset

### ISSUE THREAD

**Issue by fredalai** [Canner/WrenAI#705]
## Summary 
We need contributors to help develop end-to-end (E2E) tests for the Human Resource sample dataset. The goal is to cover the onboarding process setup go to the home page and see the suggested questions block.
 
## Description
E2E tests include:
 - Choose the Human Resource sample dataset, and ensure reach successfully reach the home page.
 - Can see the suggested questions
 - Choose the first suggested question to ask and will see the candidate results

### Note:
 - When development is complete, please execute CLI to run the tests and include the results in your PR. Ensure that at least the test you added is included, e.g.,: `yarn test:e2e e2e/specs/connectSampleHR.spec.ts`

## References:
 - Use Playwright for writing the E2E tests, please refer to the [WrenAI E2E testing README](https://github.com/Canner/WrenAI/blob/main/wren-ui/e2e/README.md) to develop.
 - Feel free to explore our existing codebase, we also have shared functions and test cases in our current test suite to help you get started: [WrenAI E2E Specs](https://github.com/Canner/WrenAI/tree/main/wren-ui/e2e/specs)

**Comment by princetoday** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by fredalai** [comment]
Hi @princetoday 

Thank you for your interest in the issues! We appreciate it.

However, for the Hacktoberfest events, we will only assign one ticket to the same person at a time.

Feel free to work on multiple issues simultaneously, but we will only assign one issue to a person at a time. This means you can submit two pull requests simultaneously, but we won't assign more than one issue to you at once.

Looking forward to your contribution!

**Comment by saai-syvendra** [comment]
Hi @fredalai!

I would like to work on this if it's available

**Comment by fredalai** [comment]
Hi @saai-syvendra 

Assigned! 😄

> And can I work on this without having an openai API key?

No, you need an Open AI API key.
