### ISSUE TITLE
The Sync Status on the modeling page is `unsync` after onboarding process finished.

### ISSUE THREAD

**Issue by onlyjackfrost** [Canner/WrenAI#706]
**Describe the bug**
The Sync Status on the modeling page has a probability of being `Undeployed changes` after the onboarding process is finished.

**To Reproduce**
1. Start a new data source / Reset your Project
2. Finish the onboarding process
3. Go to the modeling page
4. See the sync status in the header bar, seeing "Undeployed changes"

**Expected behavior**
The sync status should be "synced" with a green check icon

**Desktop (please complete the following information):**
- OS: mac 
- Browser chrome

**Wren AI Information**
- Version: 0.10.0
- LLM_PROVIDER= openai_llm
- using Postgres as the wren UI storage

**Solutions**
The cause of this bug is the order of mdl columns & models were not consistent 
In the src/apollo/server/mdl/mdlBuilder.ts file, modify the MDLBuilder constructor to sort the input columns, models, and relations by their keys.

**Comment by hpatel292-seneca** [comment]
Hi @onlyjackfrost, can I work on this issue?

**Comment by onlyjackfrost** [comment]
assigned

**Comment by hpatel292-seneca** [comment]
@onlyjackfrost I am not able to reproduce the issue.
![image](https://github.com/user-attachments/assets/ba79dd28-443a-4754-a5eb-f5d35352eef6)
I followed https://docs.getwren.ai/oss/getting_started/own_data this steps to add DuckDB data source and the provided Screenshot is what I can see after connecting to data source. Where I can find status?

**Comment by onlyjackfrost** [comment]
My bad, the "Undeployed changes" on the screenshot you provide is the "unsynced" I said.
