### ISSUE TITLE
Support Snowflake data source

### ISSUE THREAD

**Issue by andreashimin** [Canner/WrenAI#709]
**Is your feature request related to a problem? Please describe.**
Provides users with the ability to connect and set up `Snowflake` as a data source, enabling integration with distributed data processing frameworks directly within Wren AI's connection setup.

**Describe the solution you'd like**
- Add a `Snowflake` connector in [ibis-server](https://github.com/Canner/wren-engine/tree/main/ibis-server)
- Implement `Snowflake` connection handling between ibis-server and Wren UI backend.
- Create a UI form for users to set up the `Snowflake` data source (e.g., server address, port, authentication).

For more details, see `Creating a New Data Source Connector` in our [CONTRIBUTING.md](https://github.com/Canner/WrenAI/blob/main/CONTRIBUTING.md).

**Comment by druvikan** [comment]
Hi I am new to open source.I would like to work on this.

**Comment by chilijung** [comment]
@druvikan assigned, let us know how we can help you! Join our discord to meet with the team if you haven't https://discord.gg/Eg7VY6nYY5. Thank you!

**Comment by Spirizeon** [comment]
Hey, is this issue still active? If no, can i give it a try?

**Comment by chilijung** [comment]
Sure, go ahead!

**Comment by Spirizeon** [comment]
@chilijung Thanks for letting me work on it! I'll mark  the PR ready for review soon. Can you please assign this issue to me?

**Comment by chilijung** [comment]
@Spirizeon done, go ahead.

**Comment by ongdisheng** [comment]
Hi @chilijung, I noticed there's a draft PR for this feature but it hasn't had much progress recently. I’ve already submitted a PR for the Wren Engine and would be happy to take on the remaining work. Would you consider assigning the issue to me?

**Comment by chilijung** [comment]
@ongdisheng Here you go, thanks!
