### ISSUE TITLE
The data source connection password is empty

### ISSUE THREAD

**Issue by fredalai** [Canner/WrenAI#712]
## Describe the bug
When viewing the Data Source Settings page for a connected MySQL data source, the password field appears empty.

## To Reproduce
1. Connect MySQL data source
2. Go to the Home / Modeling page
3. Click "Settings" below the sidebar to view the Data Source Settings
4. See the password field is empty

## Expected behavior
Show password placeholder `************` instead of empty when viewing the Data Source Settings.

## Screenshots
![截圖 2024-10-03 下午2 47 57](https://github.com/user-attachments/assets/444ad087-083f-4608-8392-efcf425ae13c)

## Root cause
The Backend API will not return the password field information, so it will become empty if the front end does not process it.

## Solution
  - Display the password placeholder ************ instead of leaving the field empty when viewing the Data Source Settings for the following data sources: ClickHouse, MSSQL, MySQL, Postgres, and Trino.

**Comment by swarupn17** [comment]
Hello @fredalai !
I think i can do this task please can you assign it to me.
Thanks.

**Comment by cubsg** [comment]
Hi, I've added changes to the MySQLProperties.tsx file. I edited line 76, replacing the password placeholder from "input password" to "************".

**Comment by chilijung** [comment]
@swarupn17, it looks like @cubsg has been working on this issue and also submitted a PR.  Can you look into other issues that you might be interested in? Thanks!

**Comment by ongdisheng** [comment]
Hi, it seems like there's an error showing up when clicking on the save button of **Data Source Settings** page for my connected **Postgres** data source even though I didn’t modify any settings from the initial setup phase. I'm using SQLite for my Wren-ui's database. 
### Screenshot
<img src="https://github.com/user-attachments/assets/26223ea4-bdfc-44de-8de6-9ad2d785f083" width="400" />

### Console output
<img src="https://github.com/user-attachments/assets/c02868f1-7395-4a6f-ba33-04264bc9344a"  width="400" />

### Log output
![image](https://github.com/user-attachments/assets/cfb63088-9458-47c9-894d-ca61979e4f32)

**Comment by fredalai** [comment]
Hi @ongdisheng,

Thanks for catching that issue—it’s a bug.
https://github.com/Canner/WrenAI/issues/800

Thanks,
Freda

**Comment by ongdisheng** [comment]
Hi @fredalai, I noticed there hasn’t been much progress on the previous PR. Would it be alright if I step in and submit my own PR to help move things forward?

**Comment by fredalai** [comment]
@ongdisheng  Yep, sure. reassigned.
