### ISSUE TITLE
Kubernetes deployment issues

### ISSUE THREAD

**Issue by ashenoyxyz** [Canner/WrenAI#722]
**Describe the bug**

The k8s deployment configuration in the `main` branch is broken. Following are the specific issues -

- [Issue 1] wren-ibis-server is missing in the list of resources in `kustomization.yaml`
- [Issue 2] The versions for different services are outdated compared to the docker counterpart in `.env.example`

**To Reproduce**

1. Deploy on Kubernetes following the steps documented here - https://github.com/Canner/WrenAI/blob/main/deployment/kustomizations/README.md
2. Try to add a new Postgres database on the UI. This operation will fail due to Issue 1 listed above
3. wren-ai-service pod also printed a lot of error messages, specifically trying to connect to qdrant, due to outdated versions

**Expected behavior**

Kubernetes deployment should work with the documented steps

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu VM on Apple Silicon Mac (Venture 13.5.2)
- Browser [e.g. Firefox]

**Wren AI Information**

- Version: [e.g, 0.1.0]
- LLM_PROVIDER= # openai_llm, azure_openai_llm, ollama_llm.

**Additional context**

**Comment by cyyeh** [comment]
@ashenoyxyz assigned the task to you! Thanks for your contribution :)
