### ISSUE TITLE
Duplicate Required Field Warnings in Feedback Section of Footer Component

### ISSUE THREAD

**Issue by Mefisto04** [Canner/WrenAI#733]
**Describe the bug**
In the feedback section of the footer component, when submitting the form without completing required fields (e.g., the email field), the warning message "Please complete this required field" is displayed twice. This duplication negatively impacts the user interface, as it is repetitive and confusing for the user.

**To Reproduce**
- Go to the website's footer section.
- Locate the feedback form.
- Click the submit button without filling out the required fields (such as the email).
- Observe the duplicated warning message for required fields.

**Expected behavior**
The warning message should only appear once per required field, ensuring a clean and clear user interface. For instance, the error message should display only once for the email field, avoiding unnecessary repetition.

**Screenshots**
![image](https://github.com/user-attachments/assets/4b4142bf-5128-4535-9989-125392d90c56)

**Desktop (please complete the following information):**

**Wren AI Information**
- Version: [e.g, 0.1.0]
- LLM_PROVIDER= # openai_llm, azure_openai_llm, ollama_llm
- GENERATION_MODEL= # gpt-3.5-turbo, llama3:70b, etc.

**Additional context**
The duplicate warning negatively impacts the user experience. Fixing this issue would ensure cleaner UI and avoid confusion for users interacting with the feedback form in the footer section.

**Comment by chilijung** [comment]
@Mefisto04 this is using embedded code from third-party tools, will close.
