### ISSUE TITLE
UI Improvement in Website

### ISSUE THREAD

**Issue by sanketshinde3001** [Canner/WrenAI#752]
**Describe the bug**
- Buttons padding is not properly set.
-  No hover effect to cards and buttons.
- Fix some Responsiveness issues.

**To Reproduce**
![image](https://github.com/user-attachments/assets/10e2bac2-9788-4a6f-968c-60bba221667c)
No Proper padding to buttons
[see here](https://getwren.ai/oss)

![image](https://github.com/user-attachments/assets/900d408c-e2d4-407c-a6fa-a43d36a8a115)
Not able to close when we click that close button.
[See Here](https://getwren.ai/oss)

![image](https://github.com/user-attachments/assets/7b6413b9-d814-47a2-a946-da751107476e)
Cards are not showing properly in smaller screens

- No hover effect to any cards and buttons.

**Desktop (please complete the following information):**
- OS: Windows
- Browser - Chrome

**Additional context**
I'm Interested to make PR. Once assign , i'll make PR within day.

**Comment by sanketshinde3001** [comment]
Also sir if you have any UI improvement in your mind then you can add here. I'll try to do that asap.

**Comment by chilijung** [comment]
Thanks for the feedback, our issues are mainly for OSS purposes.  The website is not within scope, will close.
