### ISSUE TITLE
Issue Title: Static Footer with Unresponsive Icons

### ISSUE THREAD

**Issue by kekubhai** [Canner/WrenAI#775]
Yes, my feature request is related to a problem. The static footer section of my website is visually unappealing and lacks responsiveness, making it difficult for users to navigate and engage with the content.

Describe the solution you'd like

I would like to improve the footer's design by incorporating dynamic elements, such as hover effects on icons and links, and ensuring that it is responsive and looks good on various devices. Additionally, I'm interested in exploring creative ways to make the footer more visually appealing and engaging for users.

Describe alternatives you've considered

I have considered simply updating the footer's design with a more modern aesthetic, but I believe that incorporating dynamic elements and ensuring responsiveness would provide a much better user experience.

Additional context

[Insert any relevant screenshots or additional information about the current state of the footer section here.]

re.

**Comment by chilijung** [comment]
this is irrelavent to our oss project will close.
