### ISSUE TITLE
Failed to update data source

### ISSUE THREAD

**Issue by fredalai** [Canner/WrenAI#800]
**Describe the bug**
Failed to update data source settings

**Note** - the detailed info, please refer: https://github.com/Canner/WrenAI/issues/712#issuecomment-2426671996

**To Reproduce**
1. Use PG onboarding successfully
2. Click on Settings > Data Source Settings (See the screen showing the connection settings corresponding to the data source.)
3. Click the Save button directly without changing the connection settings

**Expected behavior**
If there are no changes, the data source setting should be updated successfully.

**Screenshots**
![image](https://github.com/user-attachments/assets/cc09f34b-ef92-4e0e-b3b6-68deb9e3b59a)

**Wren AI Information**
- Version: 0.8.1

**Additional context**

**Comment by himanshu634** [comment]
@fredalai  Can I take this?

**Comment by fredalai** [comment]
@himanshu634 assigned.

**Comment by ongdisheng** [comment]
Apparently, this issue also happens with Trino.

https://github.com/user-attachments/assets/d318118c-b2ad-4936-8ac5-4d99d2497a81

**Comment by ongdisheng** [comment]
Hi @fredalai, I’ve identified the root cause of this issue. Would it be possible to assign it to me, as it’s been inactive for a week? Thank you!

**Comment by fredalai** [comment]
@ongdisheng, of course, re-assigned!.
