### ISSUE TITLE
After creating a view, the answer generated does not indicate that it originates from a view

### ISSUE THREAD

**Issue by wwwy3y3** [Canner/WrenAI#880]
**Describe the bug**
In version 0.10.0, after creating a view, the answer generated does not indicate that it originates from a view.

**To Reproduce**
1. Go to home
2. Create a view
3. Ask a questions same with the question we saved as a view
4. Observe that the answer does not indicate it comes from the view.

**Expected behavior**
The response should clearly indicate if it originates from a view to provide transparency about the data source.

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome

**Wren AI Information**
- Version: 0.10.0
- LLM_PROVIDER= openai
- GENERATION_MODEL= gpt-4o-mini

**Comment by AryanK1511** [comment]
@wwwy3y3 This looks interesting to me. Can I give it a shot? I am not sure whether I would be able to get it to work or not but I want to try this. Are you able to assign this issue for me so that I can start working on it?

**Comment by wwwy3y3** [comment]
@AryanK1511 of course! thanks a lot.

We implemented this feature before, but it seems not working as expected right now.

As you could see from the UI logics here:
https://github.com/Canner/WrenAI/blob/8f618418316826df13ad7c78c890da08a8000d8a/wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx#L129-L157

it should show `Generated from saved view ${view name}` and clicking the view name will redirect users to the view page.

We suspect that since we change the flow of asking questions, we might break sth here. 

If the answer comes from a view, the thread response here should have a view property:
https://github.com/Canner/WrenAI/blob/8f618418316826df13ad7c78c890da08a8000d8a/wren-ui/src/apollo/server/schema.ts#L601-L606

@cyyeh, Jimmy you could share more about how AI service API works here. Might help @AryanK1511 solving this issue.

**Comment by wwwy3y3** [comment]
@AryanK1511 assigned to you.

**Comment by AryanK1511** [comment]
Cool! I'll look into this. Thank you so much for assigning this issue to me

**Comment by AryanK1511** [comment]
Sorry I took a while, got busy with some stuff. I'll start working on this by EOD

**Comment by wwwy3y3** [comment]
> Sorry I took a while, got busy with some stuff. I'll start working on this by EOD

No problem!
