### ISSUE TITLE
I can't ask questions with the E-commerca data set

### ISSUE THREAD

**Issue by marcosvolpiok** [Canner/WrenAI#998]
**Describe the bug**
When I try to do a question I get the toast: "Failed to create asking task." and this error in the firefox console:

**To Reproduce**
1. Install the e-commerce dataset
2. Ask any question
3. Click on "Ask"
4. See error in the browser and in the console

**Expected behavior**
It should answer the question

**Screenshots**
<img width="956" alt="image" src="https://github.com/user-attachments/assets/b4c468de-2dbf-48fe-bdd9-badd7e11bf33" />

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.5
- Browser Firefox, Chrome and Brave

**Wren AI Information**
- Version: 0.12.0
- LLM_PROVIDER= openai_llm
- GENERATION_MODEL= gpt-4o-mini

**Additional context**
It is a new installation of Wren AI.

**Comment by wwwy3y3** [comment]
Hi @marcosvolpiok, could you check if your OpenAI API key having the full permission?

Reference: https://docs.getwren.ai/oss/installation#2-prepare-an-openai-api-key

**Comment by marcosvolpiok** [comment]
Hi @wwwy3y3 Yes, that is the problem. I don't have any more credits.
Thanks!

**Comment by wwwy3y3** [comment]
Glad to help!
