### ISSUE TITLE
Checking OpenAI API key having full permission and worked in Wren AI at launch stage

### ISSUE THREAD

**Issue by wwwy3y3** [Canner/WrenAI#999]
**Is your feature request related to a problem? Please describe.**
Seeing users (for example: #998 ) encountered issues when asking questions without knowing it's OpenAI API key issues.

**Describe the solution you'd like**
We probably want to make a hello request to OpenAI API to make sure that the key is valid and credit balance is positive at launch stage of launcher.

**Describe alternatives you've considered**
We probably want to make the error like `insufficient quota` more clear on UI as well.

Error example
```
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

**Comment by himanshu634** [comment]
@wwwy3y3 Can I take this?

**Comment by wwwy3y3** [comment]
@himanshu634 sure, go ahead

**Comment by wwwy3y3** [comment]
@himanshu634 Hi Himanshu, keep us updated on your progress 😎

**Comment by himanshu634** [comment]
surely!

**Comment by cyyeh** [comment]
@himanshu634 This is done by another contributor. Welcome to fix another issue! Thank you for your contribution!

**Comment by himanshu634** [comment]
@cyyeh Thanks for solving it !!
